apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exporter-pvc
  namespace: one2n
  labels:
    app.kubernetes.io/instance: one2n-lab1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metrics-collector-job
  namespace: one2n
  labels:
    app.kubernetes.io/instance: one2n-lab1
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metrics-collector
            image: scraper_app:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: metrics-logs
                mountPath: /exporter-logs
            command: # Making sure that the `app.sh` script executes
              - /bin/sh
              - -c
              - ./app.sh
          restartPolicy: OnFailure
          volumes:
            - name: metrics-logs
              persistentVolumeClaim:
                claimName: exporter-pvc
---
apiVersion: v1              
kind: Pod
metadata:
  name: pvc-inspector
  namespace: one2n
  labels:
    app.kubernetes.io/instance: one2n-lab1
spec:
  containers:
  - image: busybox
    name: pvc-inspector
    command: ["tail"]
    args: ["-f", "/dev/null"] # To keep the container running just to check the files
    volumeMounts:
    - mountPath: /exporter-logs
      name: metrics-logs
  volumes:
  - name: metrics-logs
    persistentVolumeClaim:
      claimName: exporter-pvc